export const TRANSACTION_TYPES = {
  DEPOSIT: "DEPOSIT",
  EXPENSE: "EXPENSE",
  INVESTIMENT: "INVESTIMENT",
} as const;

export const TRANSACTION_CATEGORIES = {
  HOUSING: "HOUSING",
  TRANSPORTATION: "TRANSPORTATION",
  FOOD: "FOOD",
  ENTERTAINMENT: "ENTERTAINMENT",
  HEALTH: "HEALTH",
  UTILITY: "UTILITY",
  SALARY: "SALARY",
  EDUCATION: "EDUCATION",
  OTHER: "OTHER",
} as const;

export const TRANSACTION_PAYMENT_METHODS = {
  CREDIT_CARD: "CREDIT_CARD",
  DEBIT_CARD: "DEBIT_CARD",
  BANK_TRANSFER: "BANK_TRANSFER",
  BANK_SLIP: "BANK_SLIP",
  CASH: "CASH",
  PIX: "PIX",
  OTHER: "OTHER",
} as const;

// Ícones dos métodos de pagamento
export const TRANSACTION_PAYMENT_METHOD_ICONS = {
  [TRANSACTION_PAYMENT_METHODS.CREDIT_CARD]: "credit-card.svg",
  [TRANSACTION_PAYMENT_METHODS.DEBIT_CARD]: "debit-card.svg",
  [TRANSACTION_PAYMENT_METHODS.BANK_TRANSFER]: "bank-transfer.svg",
  [TRANSACTION_PAYMENT_METHODS.BANK_SLIP]: "bank-slip.svg",
  [TRANSACTION_PAYMENT_METHODS.CASH]: "money.svg",
  [TRANSACTION_PAYMENT_METHODS.PIX]: "pix.svg",
  [TRANSACTION_PAYMENT_METHODS.OTHER]: "other.svg",
};

// Labels das categorias
export const TRANSACTION_CATEGORY_LABELS = {
  [TRANSACTION_CATEGORIES.EDUCATION]: "Educação",
  [TRANSACTION_CATEGORIES.ENTERTAINMENT]: "Entretenimento",
  [TRANSACTION_CATEGORIES.FOOD]: "Alimentação",
  [TRANSACTION_CATEGORIES.HEALTH]: "Saúde",
  [TRANSACTION_CATEGORIES.HOUSING]: "Moradia",
  [TRANSACTION_CATEGORIES.OTHER]: "Outros",
  [TRANSACTION_CATEGORIES.SALARY]: "Salário",
  [TRANSACTION_CATEGORIES.TRANSPORTATION]: "Transporte",
  [TRANSACTION_CATEGORIES.UTILITY]: "Utilidades",
};

// Labels dos métodos de pagamento
export const TRANSACTION_PAYMENT_METHOD_LABELS = {
  [TRANSACTION_PAYMENT_METHODS.BANK_TRANSFER]: "Transferência Bancária",
  [TRANSACTION_PAYMENT_METHODS.BANK_SLIP]: "Boleto Bancário",
  [TRANSACTION_PAYMENT_METHODS.CASH]: "Dinheiro",
  [TRANSACTION_PAYMENT_METHODS.CREDIT_CARD]: "Cartão de Crédito",
  [TRANSACTION_PAYMENT_METHODS.DEBIT_CARD]: "Cartão de Débito",
  [TRANSACTION_PAYMENT_METHODS.OTHER]: "Outros",
  [TRANSACTION_PAYMENT_METHODS.PIX]: "Pix",
};

// Labels dos tipos de transação
export const TRANSACTION_TYPE_LABELS = {
  [TRANSACTION_TYPES.DEPOSIT]: "Depósito",
  [TRANSACTION_TYPES.EXPENSE]: "Despesa",
  [TRANSACTION_TYPES.INVESTIMENT]: "Investimento",
};

// Opções para formulários
export const TRANSACTION_TYPE_OPTIONS = [
  {
    value: TRANSACTION_TYPES.EXPENSE,
    label: TRANSACTION_TYPE_LABELS[TRANSACTION_TYPES.EXPENSE],
  },
  {
    value: TRANSACTION_TYPES.DEPOSIT,
    label: TRANSACTION_TYPE_LABELS[TRANSACTION_TYPES.DEPOSIT],
  },
  {
    value: TRANSACTION_TYPES.INVESTIMENT,
    label: TRANSACTION_TYPE_LABELS[TRANSACTION_TYPES.INVESTIMENT],
  },
];

export const TRANSACTION_PAYMENT_METHOD_OPTIONS = [
  {
    value: TRANSACTION_PAYMENT_METHODS.BANK_TRANSFER,
    label:
      TRANSACTION_PAYMENT_METHOD_LABELS[
        TRANSACTION_PAYMENT_METHODS.BANK_TRANSFER
      ],
  },
  {
    value: TRANSACTION_PAYMENT_METHODS.BANK_SLIP,
    label:
      TRANSACTION_PAYMENT_METHOD_LABELS[TRANSACTION_PAYMENT_METHODS.BANK_SLIP],
  },
  {
    value: TRANSACTION_PAYMENT_METHODS.CASH,
    label: TRANSACTION_PAYMENT_METHOD_LABELS[TRANSACTION_PAYMENT_METHODS.CASH],
  },
  {
    value: TRANSACTION_PAYMENT_METHODS.CREDIT_CARD,
    label:
      TRANSACTION_PAYMENT_METHOD_LABELS[
        TRANSACTION_PAYMENT_METHODS.CREDIT_CARD
      ],
  },
  {
    value: TRANSACTION_PAYMENT_METHODS.DEBIT_CARD,
    label:
      TRANSACTION_PAYMENT_METHOD_LABELS[TRANSACTION_PAYMENT_METHODS.DEBIT_CARD],
  },
  {
    value: TRANSACTION_PAYMENT_METHODS.OTHER,
    label: TRANSACTION_PAYMENT_METHOD_LABELS[TRANSACTION_PAYMENT_METHODS.OTHER],
  },
  {
    value: TRANSACTION_PAYMENT_METHODS.PIX,
    label: TRANSACTION_PAYMENT_METHOD_LABELS[TRANSACTION_PAYMENT_METHODS.PIX],
  },
];

export const TRANSACTION_CATEGORY_OPTIONS = [
  {
    value: TRANSACTION_CATEGORIES.EDUCATION,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORIES.EDUCATION],
  },
  {
    value: TRANSACTION_CATEGORIES.ENTERTAINMENT,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORIES.ENTERTAINMENT],
  },
  {
    value: TRANSACTION_CATEGORIES.FOOD,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORIES.FOOD],
  },
  {
    value: TRANSACTION_CATEGORIES.HEALTH,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORIES.HEALTH],
  },
  {
    value: TRANSACTION_CATEGORIES.HOUSING,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORIES.HOUSING],
  },
  {
    value: TRANSACTION_CATEGORIES.OTHER,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORIES.OTHER],
  },
  {
    value: TRANSACTION_CATEGORIES.SALARY,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORIES.SALARY],
  },
  {
    value: TRANSACTION_CATEGORIES.TRANSPORTATION,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORIES.TRANSPORTATION],
  },
  {
    value: TRANSACTION_CATEGORIES.UTILITY,
    label: TRANSACTION_CATEGORY_LABELS[TRANSACTION_CATEGORIES.UTILITY],
  },
];

// Tipos TypeScript para type safety
export type TransactionType =
  (typeof TRANSACTION_TYPES)[keyof typeof TRANSACTION_TYPES];
export type TransactionCategory =
  (typeof TRANSACTION_CATEGORIES)[keyof typeof TRANSACTION_CATEGORIES];
export type TransactionPaymentMethod =
  (typeof TRANSACTION_PAYMENT_METHODS)[keyof typeof TRANSACTION_PAYMENT_METHODS];
