export const TRANSACTION_TYPES = {
  DEPOSIT: "DEPOSIT",
  EXPENSE: "EXPENSE",
} as const;

export const TRANSACTION_CATEGORIES = {
  // Categorias para DESPESAS (EXPENSE)
  HOUSING: "HOUSING",
  TRANSPORTATION: "TRANSPORTATION",
  FOOD: "FOOD",
  SHOPPING: "SHOPPING",
  ENTERTAINMENT: "ENTERTAINMENT",
  HEALTH: "HEALTH",
  UTILITY: "UTILITY",
  EDUCATION: "EDUCATION",
  PETS: "PETS",
  BEAUTY: "BEAUTY",
  INSURANCE: "INSURANCE",
  TAXES: "TAXES",
  LOAN_EXPENSE: "LOAN_EXPENSE",
  // Categorias para DEPÓSITOS (DEPOSIT)
  SALARY: "SALARY",
  FREELANCE: "FREELANCE",
  BUSINESS: "BUSINESS",
  INVESTMENT: "INVESTMENT",
  BONUS: "BONUS",
  GIFT: "GIFT",
  REFUND: "REFUND",
  RENTAL: "RENTAL",
  SIDE_HUSTLE: "SIDE_HUSTLE",
  LOAN_INCOME: "LOAN_INCOME",
  // Fallback
  OTHER: "OTHER",
} as const;

export const TRANSACTION_PAYMENT_METHODS = {
  CREDIT_CARD: "CREDIT_CARD",
  DEBIT_CARD: "DEBIT_CARD",
  BANK_TRANSFER: "BANK_TRANSFER",
  BANK_SLIP: "BANK_SLIP",
  CASH: "CASH",
  PIX: "PIX",
  OTHER: "OTHER",
} as const;

// Ícones dos métodos de pagamento
export const TRANSACTION_PAYMENT_METHOD_ICONS = {
  [TRANSACTION_PAYMENT_METHODS.CREDIT_CARD]: "credit-card.svg",
  [TRANSACTION_PAYMENT_METHODS.DEBIT_CARD]: "debit-card.svg",
  [TRANSACTION_PAYMENT_METHODS.BANK_TRANSFER]: "bank-transfer.svg",
  [TRANSACTION_PAYMENT_METHODS.BANK_SLIP]: "bank-slip.svg",
  [TRANSACTION_PAYMENT_METHODS.CASH]: "money.svg",
  [TRANSACTION_PAYMENT_METHODS.PIX]: "pix.svg",
  [TRANSACTION_PAYMENT_METHODS.OTHER]: "other.svg",
};

// Categorias para DESPESAS (EXPENSE)
export const EXPENSE_CATEGORIES = {
  [TRANSACTION_CATEGORIES.HOUSING]: "Moradia",
  [TRANSACTION_CATEGORIES.TRANSPORTATION]: "Transporte",
  [TRANSACTION_CATEGORIES.FOOD]: "Alimentação",
  [TRANSACTION_CATEGORIES.SHOPPING]: "Compras",
  [TRANSACTION_CATEGORIES.ENTERTAINMENT]: "Entretenimento",
  [TRANSACTION_CATEGORIES.HEALTH]: "Saúde",
  [TRANSACTION_CATEGORIES.UTILITY]: "Utilidades",
  [TRANSACTION_CATEGORIES.EDUCATION]: "Educação",
  [TRANSACTION_CATEGORIES.PETS]: "Pets",
  [TRANSACTION_CATEGORIES.BEAUTY]: "Beleza & Cuidados",
  [TRANSACTION_CATEGORIES.INSURANCE]: "Seguros",
  [TRANSACTION_CATEGORIES.TAXES]: "Impostos & Taxas",
  [TRANSACTION_CATEGORIES.LOAN_EXPENSE]: "Empréstimos",
  [TRANSACTION_CATEGORIES.OTHER]: "Outros",
};

// Categorias para DEPÓSITOS (DEPOSIT)
export const DEPOSIT_CATEGORIES = {
  [TRANSACTION_CATEGORIES.SALARY]: "Salário",
  [TRANSACTION_CATEGORIES.FREELANCE]: "Freelance",
  [TRANSACTION_CATEGORIES.BUSINESS]: "Negócios",
  [TRANSACTION_CATEGORIES.INVESTMENT]: "Investimentos",
  [TRANSACTION_CATEGORIES.BONUS]: "Bônus & Comissões",
  [TRANSACTION_CATEGORIES.GIFT]: "Presentes & Doações",
  [TRANSACTION_CATEGORIES.REFUND]: "Reembolsos",
  [TRANSACTION_CATEGORIES.RENTAL]: "Aluguel Recebido",
  [TRANSACTION_CATEGORIES.SIDE_HUSTLE]: "Renda Extra",
  [TRANSACTION_CATEGORIES.LOAN_INCOME]: "Empréstimos",
  [TRANSACTION_CATEGORIES.OTHER]: "Outros",
};

// Labels unificadas (para compatibilidade com código existente)
export const TRANSACTION_CATEGORY_LABELS = {
  ...EXPENSE_CATEGORIES,
  ...DEPOSIT_CATEGORIES,
};

// Labels dos métodos de pagamento
export const TRANSACTION_PAYMENT_METHOD_LABELS = {
  [TRANSACTION_PAYMENT_METHODS.BANK_TRANSFER]: "Transferência Bancária",
  [TRANSACTION_PAYMENT_METHODS.BANK_SLIP]: "Boleto Bancário",
  [TRANSACTION_PAYMENT_METHODS.CASH]: "Dinheiro",
  [TRANSACTION_PAYMENT_METHODS.CREDIT_CARD]: "Cartão de Crédito",
  [TRANSACTION_PAYMENT_METHODS.DEBIT_CARD]: "Cartão de Débito",
  [TRANSACTION_PAYMENT_METHODS.OTHER]: "Outros",
  [TRANSACTION_PAYMENT_METHODS.PIX]: "Pix",
};

// Labels dos tipos de transação
export const TRANSACTION_TYPE_LABELS = {
  [TRANSACTION_TYPES.DEPOSIT]: "Depósito",
  [TRANSACTION_TYPES.EXPENSE]: "Despesa",
};

// Opções para formulários - DESPESAS
export const EXPENSE_CATEGORY_OPTIONS = [
  {
    value: TRANSACTION_CATEGORIES.HOUSING,
    label: EXPENSE_CATEGORIES[TRANSACTION_CATEGORIES.HOUSING],
  },
  {
    value: TRANSACTION_CATEGORIES.TRANSPORTATION,
    label: EXPENSE_CATEGORIES[TRANSACTION_CATEGORIES.TRANSPORTATION],
  },
  {
    value: TRANSACTION_CATEGORIES.FOOD,
    label: EXPENSE_CATEGORIES[TRANSACTION_CATEGORIES.FOOD],
  },
  {
    value: TRANSACTION_CATEGORIES.SHOPPING,
    label: EXPENSE_CATEGORIES[TRANSACTION_CATEGORIES.SHOPPING],
  },
  {
    value: TRANSACTION_CATEGORIES.ENTERTAINMENT,
    label: EXPENSE_CATEGORIES[TRANSACTION_CATEGORIES.ENTERTAINMENT],
  },
  {
    value: TRANSACTION_CATEGORIES.HEALTH,
    label: EXPENSE_CATEGORIES[TRANSACTION_CATEGORIES.HEALTH],
  },
  {
    value: TRANSACTION_CATEGORIES.UTILITY,
    label: EXPENSE_CATEGORIES[TRANSACTION_CATEGORIES.UTILITY],
  },
  {
    value: TRANSACTION_CATEGORIES.EDUCATION,
    label: EXPENSE_CATEGORIES[TRANSACTION_CATEGORIES.EDUCATION],
  },
  {
    value: TRANSACTION_CATEGORIES.PETS,
    label: EXPENSE_CATEGORIES[TRANSACTION_CATEGORIES.PETS],
  },
  {
    value: TRANSACTION_CATEGORIES.BEAUTY,
    label: EXPENSE_CATEGORIES[TRANSACTION_CATEGORIES.BEAUTY],
  },
  {
    value: TRANSACTION_CATEGORIES.INSURANCE,
    label: EXPENSE_CATEGORIES[TRANSACTION_CATEGORIES.INSURANCE],
  },
  {
    value: TRANSACTION_CATEGORIES.TAXES,
    label: EXPENSE_CATEGORIES[TRANSACTION_CATEGORIES.TAXES],
  },
  {
    value: TRANSACTION_CATEGORIES.LOAN_EXPENSE,
    label: EXPENSE_CATEGORIES[TRANSACTION_CATEGORIES.LOAN_EXPENSE],
  },
  {
    value: TRANSACTION_CATEGORIES.OTHER,
    label: EXPENSE_CATEGORIES[TRANSACTION_CATEGORIES.OTHER],
  },
];

// Opções para formulários - DEPÓSITOS
export const DEPOSIT_CATEGORY_OPTIONS = [
  {
    value: TRANSACTION_CATEGORIES.SALARY,
    label: DEPOSIT_CATEGORIES[TRANSACTION_CATEGORIES.SALARY],
  },
  {
    value: TRANSACTION_CATEGORIES.FREELANCE,
    label: DEPOSIT_CATEGORIES[TRANSACTION_CATEGORIES.FREELANCE],
  },
  {
    value: TRANSACTION_CATEGORIES.BUSINESS,
    label: DEPOSIT_CATEGORIES[TRANSACTION_CATEGORIES.BUSINESS],
  },
  {
    value: TRANSACTION_CATEGORIES.INVESTMENT,
    label: DEPOSIT_CATEGORIES[TRANSACTION_CATEGORIES.INVESTMENT],
  },
  {
    value: TRANSACTION_CATEGORIES.BONUS,
    label: DEPOSIT_CATEGORIES[TRANSACTION_CATEGORIES.BONUS],
  },
  {
    value: TRANSACTION_CATEGORIES.GIFT,
    label: DEPOSIT_CATEGORIES[TRANSACTION_CATEGORIES.GIFT],
  },
  {
    value: TRANSACTION_CATEGORIES.REFUND,
    label: DEPOSIT_CATEGORIES[TRANSACTION_CATEGORIES.REFUND],
  },
  {
    value: TRANSACTION_CATEGORIES.RENTAL,
    label: DEPOSIT_CATEGORIES[TRANSACTION_CATEGORIES.RENTAL],
  },
  {
    value: TRANSACTION_CATEGORIES.SIDE_HUSTLE,
    label: DEPOSIT_CATEGORIES[TRANSACTION_CATEGORIES.SIDE_HUSTLE],
  },
  {
    value: TRANSACTION_CATEGORIES.LOAN_INCOME,
    label: DEPOSIT_CATEGORIES[TRANSACTION_CATEGORIES.LOAN_INCOME],
  },
  {
    value: TRANSACTION_CATEGORIES.OTHER,
    label: DEPOSIT_CATEGORIES[TRANSACTION_CATEGORIES.OTHER],
  },
];

// Opções para formulários (para compatibilidade)
export const TRANSACTION_CATEGORY_OPTIONS = [
  ...EXPENSE_CATEGORY_OPTIONS,
  ...DEPOSIT_CATEGORY_OPTIONS,
];

export const TRANSACTION_TYPE_OPTIONS = [
  {
    value: TRANSACTION_TYPES.EXPENSE,
    label: TRANSACTION_TYPE_LABELS[TRANSACTION_TYPES.EXPENSE],
  },
  {
    value: TRANSACTION_TYPES.DEPOSIT,
    label: TRANSACTION_TYPE_LABELS[TRANSACTION_TYPES.DEPOSIT],
  },
];

export const TRANSACTION_PAYMENT_METHOD_OPTIONS = [
  {
    value: TRANSACTION_PAYMENT_METHODS.BANK_TRANSFER,
    label:
      TRANSACTION_PAYMENT_METHOD_LABELS[
        TRANSACTION_PAYMENT_METHODS.BANK_TRANSFER
      ],
  },
  {
    value: TRANSACTION_PAYMENT_METHODS.BANK_SLIP,
    label:
      TRANSACTION_PAYMENT_METHOD_LABELS[TRANSACTION_PAYMENT_METHODS.BANK_SLIP],
  },
  {
    value: TRANSACTION_PAYMENT_METHODS.CASH,
    label: TRANSACTION_PAYMENT_METHOD_LABELS[TRANSACTION_PAYMENT_METHODS.CASH],
  },
  {
    value: TRANSACTION_PAYMENT_METHODS.CREDIT_CARD,
    label:
      TRANSACTION_PAYMENT_METHOD_LABELS[
        TRANSACTION_PAYMENT_METHODS.CREDIT_CARD
      ],
  },
  {
    value: TRANSACTION_PAYMENT_METHODS.DEBIT_CARD,
    label:
      TRANSACTION_PAYMENT_METHOD_LABELS[TRANSACTION_PAYMENT_METHODS.DEBIT_CARD],
  },
  {
    value: TRANSACTION_PAYMENT_METHODS.OTHER,
    label: TRANSACTION_PAYMENT_METHOD_LABELS[TRANSACTION_PAYMENT_METHODS.OTHER],
  },
  {
    value: TRANSACTION_PAYMENT_METHODS.PIX,
    label: TRANSACTION_PAYMENT_METHOD_LABELS[TRANSACTION_PAYMENT_METHODS.PIX],
  },
];

// Função utilitária para obter categorias baseadas no tipo
export const getCategoriesByType = (type: TransactionType) => {
  return type === TRANSACTION_TYPES.EXPENSE
    ? EXPENSE_CATEGORY_OPTIONS
    : DEPOSIT_CATEGORY_OPTIONS;
};

// Função utilitária para obter label da categoria
export const getCategoryLabel = (category: TransactionCategory) => {
  return TRANSACTION_CATEGORY_LABELS[category] || "Outros";
};

// Tipos TypeScript para type safety
export type TransactionType =
  (typeof TRANSACTION_TYPES)[keyof typeof TRANSACTION_TYPES];
export type TransactionCategory =
  (typeof TRANSACTION_CATEGORIES)[keyof typeof TRANSACTION_CATEGORIES];
export type TransactionPaymentMethod =
  (typeof TRANSACTION_PAYMENT_METHODS)[keyof typeof TRANSACTION_PAYMENT_METHODS];
